const fs = require('fs');
const path = require('path');

const DB_DIR = path.join(__dirname, '../../Backend/database');
const OUTPUT_FILE = path.join(__dirname, '../SCHEMA_DICTIONARY.md');

function updateSchemaDictionary() {
    let markdown = `# RetailNodeV2 - Database Schema Dictionary\n\n`;
    markdown += `> **CTO RULE:** Before suggesting a new database table, you MUST check this dictionary. Do not duplicate existing tables (e.g. creating \`Vendors\` when \`Parties\` exists).\n\n`;
    markdown += `> **AUTO-GENERATED:** This file is automatically generated by \`.agents/scripts/update_schema_dictionary.js\`. Do not edit manually.\n\n`;
    markdown += `## Tables List\n\n`;

    if (!fs.existsSync(DB_DIR)) {
        console.error(`Database directory not found at: ${DB_DIR}`);
        return;
    }

    const files = fs.readdirSync(DB_DIR)
        .filter(file => file.endsWith('.sql'))
        .sort();

    files.forEach(file => {
        const filePath = path.join(DB_DIR, file);
        const content = fs.readFileSync(filePath, 'utf-8');

        // Regex to extract CREATE TABLE statements
        const tableRegex = /CREATE TABLE\s+(?:IF NOT EXISTS\s+)?`?(\w+)`?\s*\(([\s\S]*?)\)\s*(?:ENGINE|;)/gi;
        let match;
        let hasTables = false;

        while ((match = tableRegex.exec(content)) !== null) {
            if (!hasTables) {
                markdown += `### Source: \`${file}\`\n`;
                hasTables = true;
            }

            const tableName = match[1];
            const schemaBlock = match[2];
            markdown += `#### \`${tableName}\`\n`;

            const lines = schemaBlock.split('\n');
            lines.forEach(line => {
                const trimmed = line.trim();
                // Skip constraints, comments, and empty lines
                if (trimmed && !trimmed.startsWith('--') && !trimmed.startsWith('PRIMARY') && !trimmed.startsWith('FOREIGN') && !trimmed.startsWith('UNIQUE') && !trimmed.startsWith('KEY') && !trimmed.startsWith('CONSTRAINT')) {
                    const colMatch = trimmed.match(/^`?(\w+)`?\s+(.*)/);
                    if (colMatch) {
                        const colName = colMatch[1];
                        const colDef = colMatch[2].replace(/,$/, '').trim();
                        markdown += `- **${colName}**: ${colDef}\n`;
                    }
                }
            });
            markdown += `\n`;
        }
    });

    fs.writeFileSync(OUTPUT_FILE, markdown, 'utf-8');
    console.log(`Successfully updated: ${OUTPUT_FILE}`);
}

updateSchemaDictionary();
